version: '3'
services:
  database:
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
